ktor:
    application:
        modules:
            - com.supervet.ApplicationKt.module
    deployment:
        port: 8080

database:
    host: ${DATABASE_HOST}
    port: ${DATABASE_PORT}
    database: ${DATABASE_NAME}
    user: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
