services:
  - name: supervet-api
    type: web
    runtime: docker
    plan: free
    region: frankfurt
    dockerfilePath: ./supervet/Dockerfile
    dockerContext: ./supervet

  - name: supervet-web
    type: web
    runtime: node
    plan: free
    region: frankfurt
    buildCommand: npm install; npm run build
    startCommand: npm run start
    rootDir: ./web

databases:

  - name: supervet-db
    postgresMajorVersion: "16"
    region: frankfurt
    plan: free
    databaseName: supervet
