
services:
  - name: supervet-api
    type: web
    runtime: docker
    plan: free
    region: frankfurt
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    envVars:
      - key: DATABASE_HOST
        fromDatabase:
          name: supervet-db
          property: host
      - key: DATABASE_PORT
        fromDatabase:
          name: supervet-db
          property: port
      - key: DATABASE_NAME
        fromDatabase:
          name: supervet-db
          property: database
      - key: DATABASE_USER
        fromDatabase:
          name: supervet-db
          property: user
      - key: DATABASE_PASSWORD
        fromDatabase:
          name: supervet-db
          property: password

  - name: supervet-web
    type: web
    runtime: node
    plan: free
    region: frankfurt
    buildCommand: npm install; npm run build
    startCommand: npm run start
    rootDir: ./frontend
    envVars:
      - key: API_URL
        fromService:
          name: supervet-api
          type: web
          property: host
      - key: NEXT_PUBLIC_API_URL
        fromService:
          name: supervet-api
          type: web
          property: host

databases:
  - name: supervet-db
    postgresMajorVersion: "16"
    region: frankfurt
    plan: free
    databaseName: supervet