services:
  - name: supervet-api
    type: web
    runtime: docker
    plan: free
    region: frankfurt
    dockerfilePath: ./supervet/Dockerfile
    dockerContext: ./supervet

  - name: supervet-web
    type: web
    runtime: node
    plan: free
    region: frankfurt
    buildCommand: npm install; npm run build
    startCommand: npm run start
    rootDir: ./web

databases:

  - name: supervet-db
    postgresMajorVersion: "16"
    region: frankfurt
    plan: free
    databaseName: supervet
    envVars:
    - key: DATABASE_HOST
      fromDatabase:
      name: supervet-db
      property: Hostname
    - key: DATABASE_PORT
      fromDatabase:
      name: supervet-db
      property: Port
    - key: DATABASE_NAME
      fromDatabase:
      name: supervet-db
      property: Name
    - key: DATABASE_USER
      fromDatabase:
      name: supervet-db
      property: Username
    - key: DATABASE_PASSWORD
      fromDatabase:
      name: supervet-db
      property: Password
